#!/bin/sh

set -e

json=$(cat config.json)

source "$(dirname $0)/build.sh"

echo $json | docker run \
  -i \
  --rm \
    dnepomnaschy/s3-resource-simple \
    /opt/resource/check
#    18fgsa/s3-resource-simple \
